import type { Locale } from "./types";

export const siteCopy = {
  en: {
    langName: "English",
    skip: "Skip to main content",
    menu: "Menu",
    navigation: "Primary navigation",
    languageNavigation: "Language selection",
    work: "Work",
    about: "About",
    contact: "Contact",
    github: "GitHub",
    linkedin: "LinkedIn",
    viewWork: "View technical work",
    currentVenture: "Currently",
    exploreVenture: "Explore Reperta",
    ventureMethodology: "How Reperta investigates",
    ventureMission: "Investigate problems. Build companies.",
    selectedWork: "Technical work",
    selectedWorkIntro:
      "Four projects that show my technical background in manufacturing, quality, and applied AI. Explore my contribution and the evidence behind each result.",
    selectedWorkReelLabel: "Selected work reel",
    selectedWorkPrevious: "Previous project",
    selectedWorkNext: "Next project",
    selectedWorkIndicators: "Choose a project",
    selectedWorkOf: "of",
    inDevelopment: "In development",
    caseInDevelopment: "Case study in development",
    viewCase: "Read the case study",
    principlesEyebrow: "Working principles",
    principlesTitle: "Evidence before confidence",
    principles: [
      {
        title: "Clarity",
        body: "Define the question, the vocabulary, and the decision boundary before adding tools.",
      },
      {
        title: "Traceability",
        body: "Connect public statements to versioned sources that another person can inspect.",
      },
      {
        title: "Validation",
        body: "Reconcile results across independent layers and record the assumptions that shape them.",
      },
      {
        title: "Honest limits",
        body: "State what the evidence cannot establish as visibly as what it supports.",
      },
    ],
    capabilitiesEyebrow: "Verifiable capabilities",
    capabilitiesTitle: "A technical foundation for building",
    capabilities: [
      "Manufacturing-data quality review",
      "Python and SQL analytical workflows",
      "PostgreSQL persistence and reconciliation",
      "Statistical validation against a reference tool",
      "Decision-focused Power BI communication",
      "Automated checks and versioned evidence",
      "Hybrid retrieval and evaluation for manufacturing RAG",
    ],
    aboutEyebrow: "About",
    aboutTitle: "Research, decide, build",
    aboutBody:
      "I'm Jehu Lara, founder and CEO of Reperta. I lead an independent studio in Monterrey focused on understanding business problems and assessing opportunities to build new companies. My technical work in quality, data, and applied AI informs how I investigate, test assumptions, and develop prototypes.",
    contactEyebrow: "Contact",
    contactTitle: "What problem is worth solving?",
    contactBody:
      "Let's talk about business problems and potential collaborations. You can also explore my technical work on GitHub or connect on LinkedIn.",
    visitGithub: "Visit Jehu Lara on GitHub",
    visitLinkedin: "Connect with Jehu Lara on LinkedIn",
    archiveEyebrow: "Project archive",
    archiveTitle: "Work",
    archiveIntro:
      "Explore four projects through their problem, my contribution, and the results supported by the evidence.",
    status: "Status",
    published: "Published",
    capabilitiesDemonstrated: "Capabilities demonstrated",
    period: "Evidence period",
    caseStudy: "Case study",
    provenance: "View full provenance",
    limitsLabel: "Evidence limits",
    imageExpand: "Enlarge the Power BI evidence",
    imageClose: "Close enlarged image",
    imageFull: "Open the full-resolution Power BI evidence",
    presentationLabel: "QualityOps evidence presentation",
    presentationPrevious: "Previous",
    presentationNext: "Next",
    presentationExpand: "Enlarge current slide",
    presentationClose: "Close presentation",
    presentationThumbnails: "Presentation slides",
    presentationOf: "of",
    externalLink: "opens in a new tab",
    footerNote: "Founder & CEO of Reperta · Monterrey, Mexico",
  },
  es: {
    langName: "Español",
    skip: "Saltar al contenido principal",
    menu: "Menú",
    navigation: "Navegación principal",
    languageNavigation: "Selección de idioma",
    work: "Proyectos",
    about: "Acerca de",
    contact: "Contacto",
    github: "GitHub",
    linkedin: "LinkedIn",
    viewWork: "Ver proyectos técnicos",
    currentVenture: "Actualmente",
    exploreVenture: "Conocer Reperta",
    ventureMethodology: "Cómo investiga Reperta",
    ventureMission: "Investigar problemas. Construir empresas.",
    selectedWork: "Proyectos técnicos",
    selectedWorkIntro:
      "Cuatro proyectos que muestran mi trayectoria técnica en manufactura, calidad e IA aplicada. Explora mi aportación y la evidencia detrás de cada resultado.",
    selectedWorkReelLabel: "Reel de trabajo seleccionado",
    selectedWorkPrevious: "Proyecto anterior",
    selectedWorkNext: "Proyecto siguiente",
    selectedWorkIndicators: "Elegir un proyecto",
    selectedWorkOf: "de",
    inDevelopment: "En desarrollo",
    caseInDevelopment: "Caso de estudio en desarrollo",
    viewCase: "Leer el caso de estudio",
    principlesEyebrow: "Principios de trabajo",
    principlesTitle: "Evidencia antes que certeza",
    principles: [
      {
        title: "Claridad",
        body: "Definir la pregunta, el vocabulario y el límite de decisión antes de añadir herramientas.",
      },
      {
        title: "Trazabilidad",
        body: "Conectar las afirmaciones públicas con fuentes versionadas que otra persona pueda inspeccionar.",
      },
      {
        title: "Validación",
        body: "Reconciliar resultados entre capas independientes y registrar los supuestos que los condicionan.",
      },
      {
        title: "Límites honestos",
        body: "Mostrar lo que la evidencia no establece con la misma claridad que lo que sí respalda.",
      },
    ],
    capabilitiesEyebrow: "Capacidades verificables",
    capabilitiesTitle: "Una base técnica para construir",
    capabilities: [
      "Revisión de calidad de datos de manufactura",
      "Flujos analíticos con Python y SQL",
      "Persistencia y reconciliación en PostgreSQL",
      "Validación estadística contra una herramienta de referencia",
      "Comunicación de decisiones con Power BI",
      "Comprobaciones automatizadas y evidencia versionada",
      "Recuperación híbrida y evaluación de RAG para manufactura",
    ],
    aboutEyebrow: "Acerca de",
    aboutTitle: "Investigar, decidir, construir",
    aboutBody:
      "Soy Jehu Lara, fundador y CEO de Reperta. Dirijo un estudio independiente de Monterrey enfocado en entender problemas de negocio y evaluar oportunidades para construir nuevas empresas. Mi trabajo técnico en calidad, datos e IA aplicada aporta la base para investigar, probar supuestos y desarrollar prototipos.",
    contactEyebrow: "Contacto",
    contactTitle: "¿Qué problema vale la pena resolver?",
    contactBody:
      "Conversemos sobre problemas de negocio y posibles colaboraciones. También puedes explorar mi trabajo técnico en GitHub o conectar conmigo en LinkedIn.",
    visitGithub: "Visitar a Jehu Lara en GitHub",
    visitLinkedin: "Conectar con Jehu Lara en LinkedIn",
    archiveEyebrow: "Archivo de proyectos",
    archiveTitle: "Proyectos",
    archiveIntro:
      "Explora cuatro proyectos a través de su problema, mi aportación y los resultados respaldados por la evidencia.",
    status: "Estado",
    published: "Publicado",
    capabilitiesDemonstrated: "Capacidades demostradas",
    period: "Periodo de evidencia",
    caseStudy: "Caso de estudio",
    provenance: "Ver procedencia completa",
    limitsLabel: "Límites de la evidencia",
    imageExpand: "Ampliar la evidencia de Power BI",
    imageClose: "Cerrar imagen ampliada",
    imageFull: "Abrir la evidencia de Power BI en resolución completa",
    presentationLabel: "Presentación de evidencia de QualityOps",
    presentationPrevious: "Anterior",
    presentationNext: "Siguiente",
    presentationExpand: "Ampliar diapositiva actual",
    presentationClose: "Cerrar presentación",
    presentationThumbnails: "Diapositivas de la presentación",
    presentationOf: "de",
    externalLink: "se abre en una pestaña nueva",
    footerNote: "Fundador y CEO de Reperta · Monterrey, México",
  },
} as const satisfies Record<Locale, object>;
