import type { Locale } from "./types";

export const siteCopy = {
  en: {
    langName: "English",
    skip: "Skip to main content",
    menu: "Menu",
    navigation: "Primary navigation",
    languageNavigation: "Language selection",
    work: "Work",
    about: "About",
    contact: "Contact",
    github: "GitHub",
    linkedin: "LinkedIn",
    viewWork: "View selected work",
    selectedWork: "Selected work",
    selectedWorkIntro:
      "Two published cases make their evidence, limits, and current verification state inspectable.",
    selectedWorkReelLabel: "Selected work reel",
    selectedWorkPrevious: "Previous project",
    selectedWorkNext: "Next project",
    selectedWorkIndicators: "Choose a project",
    selectedWorkOf: "of",
    inDevelopment: "In development",
    caseInDevelopment: "Case study in development",
    viewCase: "Read the case study",
    principlesEyebrow: "Working principles",
    principlesTitle: "Evidence before confidence",
    principles: [
      {
        title: "Clarity",
        body: "Define the question, the vocabulary, and the decision boundary before adding tools.",
      },
      {
        title: "Traceability",
        body: "Connect public statements to versioned sources that another person can inspect.",
      },
      {
        title: "Validation",
        body: "Reconcile results across independent layers and record the assumptions that shape them.",
      },
      {
        title: "Honest limits",
        body: "State what the evidence cannot establish as visibly as what it supports.",
      },
    ],
    capabilitiesEyebrow: "Verifiable capabilities",
    capabilitiesTitle: "A practical quality-and-analytics toolkit",
    capabilities: [
      "Manufacturing-data quality review",
      "Python and SQL analytical workflows",
      "PostgreSQL persistence and reconciliation",
      "Statistical validation against a reference tool",
      "Decision-focused Power BI communication",
      "Automated checks and versioned evidence",
    ],
    aboutEyebrow: "About",
    aboutTitle: "A portfolio built around judgment",
    aboutBody:
      "Quality & Analytics Engineer is my professional positioning, not a claim about a current employer or job title. I am targeting Quality Engineer, Manufacturing Data Analyst, and Analytics Engineer roles. This portfolio shows how I frame analytical risk, make assumptions reviewable, and stop conclusions at the edge of the evidence.",
    contactEyebrow: "Contact",
    contactTitle: "Review the work or start a conversation",
    contactBody:
      "Email is available for direct contact, GitHub contains the source and versioned evidence behind the published cases, and LinkedIn is available for professional contact.",
    visitGithub: "Visit Jehu Lara on GitHub",
    visitLinkedin: "Connect with Jehu Lara on LinkedIn",
    archiveEyebrow: "Project archive",
    archiveTitle: "Work",
    archiveIntro:
      "An extensible record of technical projects, each separated into scope, evidence, findings, and explicit limits.",
    status: "Status",
    published: "Published",
    capabilitiesDemonstrated: "Capabilities demonstrated",
    period: "Evidence period",
    caseStudy: "Case study",
    provenance: "View full provenance",
    limitsLabel: "Evidence limits",
    imageExpand: "Enlarge the Power BI evidence",
    imageClose: "Close enlarged image",
    imageFull: "Open the full-resolution Power BI evidence",
    presentationLabel: "QualityOps evidence presentation",
    presentationPrevious: "Previous",
    presentationNext: "Next",
    presentationExpand: "Enlarge current slide",
    presentationClose: "Close presentation",
    presentationThumbnails: "Presentation slides",
    presentationOf: "of",
    externalLink: "opens in a new tab",
    footerNote: "Personal evidence portfolio · Built for careful review",
  },
  es: {
    langName: "Español",
    skip: "Saltar al contenido principal",
    menu: "Menú",
    navigation: "Navegación principal",
    languageNavigation: "Selección de idioma",
    work: "Proyectos",
    about: "Acerca de",
    contact: "Contacto",
    github: "GitHub",
    linkedin: "LinkedIn",
    viewWork: "Ver trabajo seleccionado",
    selectedWork: "Trabajo seleccionado",
    selectedWorkIntro:
      "Dos casos publicados hacen inspeccionables su evidencia, límites y estado actual de verificación.",
    selectedWorkReelLabel: "Reel de trabajo seleccionado",
    selectedWorkPrevious: "Proyecto anterior",
    selectedWorkNext: "Proyecto siguiente",
    selectedWorkIndicators: "Elegir un proyecto",
    selectedWorkOf: "de",
    inDevelopment: "En desarrollo",
    caseInDevelopment: "Caso de estudio en desarrollo",
    viewCase: "Leer el caso de estudio",
    principlesEyebrow: "Principios de trabajo",
    principlesTitle: "Evidencia antes que certeza",
    principles: [
      {
        title: "Claridad",
        body: "Definir la pregunta, el vocabulario y el límite de decisión antes de añadir herramientas.",
      },
      {
        title: "Trazabilidad",
        body: "Conectar las afirmaciones públicas con fuentes versionadas que otra persona pueda inspeccionar.",
      },
      {
        title: "Validación",
        body: "Reconciliar resultados entre capas independientes y registrar los supuestos que los condicionan.",
      },
      {
        title: "Límites honestos",
        body: "Mostrar lo que la evidencia no establece con la misma claridad que lo que sí respalda.",
      },
    ],
    capabilitiesEyebrow: "Capacidades verificables",
    capabilitiesTitle: "Herramientas prácticas de calidad y análisis",
    capabilities: [
      "Revisión de calidad de datos de manufactura",
      "Flujos analíticos con Python y SQL",
      "Persistencia y reconciliación en PostgreSQL",
      "Validación estadística contra una herramienta de referencia",
      "Comunicación de decisiones con Power BI",
      "Comprobaciones automatizadas y evidencia versionada",
    ],
    aboutEyebrow: "Acerca de",
    aboutTitle: "Un portafolio centrado en el criterio",
    aboutBody:
      "Quality & Analytics Engineer es mi posicionamiento profesional, no una afirmación sobre un empleador o puesto actual. Busco oportunidades como Quality Engineer, Manufacturing Data Analyst y Analytics Engineer. Este portafolio muestra cómo delimito el riesgo analítico, vuelvo revisables los supuestos y detengo las conclusiones donde termina la evidencia.",
    contactEyebrow: "Contacto",
    contactTitle: "Revisa el trabajo o inicia una conversación",
    contactBody:
      "El correo está disponible para contacto directo, GitHub contiene el código fuente y la evidencia versionada del caso publicado, y LinkedIn está disponible para contacto profesional.",
    visitGithub: "Visitar a Jehu Lara en GitHub",
    visitLinkedin: "Conectar con Jehu Lara en LinkedIn",
    archiveEyebrow: "Archivo de proyectos",
    archiveTitle: "Proyectos",
    archiveIntro:
      "Un registro extensible de proyectos técnicos, cada uno separado en alcance, evidencia, hallazgos y límites explícitos.",
    status: "Estado",
    published: "Publicado",
    capabilitiesDemonstrated: "Capacidades demostradas",
    period: "Periodo de evidencia",
    caseStudy: "Caso de estudio",
    provenance: "Ver procedencia completa",
    limitsLabel: "Límites de la evidencia",
    imageExpand: "Ampliar la evidencia de Power BI",
    imageClose: "Cerrar imagen ampliada",
    imageFull: "Abrir la evidencia de Power BI en resolución completa",
    presentationLabel: "Presentación de evidencia de QualityOps",
    presentationPrevious: "Anterior",
    presentationNext: "Siguiente",
    presentationExpand: "Ampliar diapositiva actual",
    presentationClose: "Cerrar presentación",
    presentationThumbnails: "Diapositivas de la presentación",
    presentationOf: "de",
    externalLink: "se abre en una pestaña nueva",
    footerNote: "Portafolio personal de evidencia · Diseñado para revisión cuidadosa",
  },
} as const satisfies Record<Locale, object>;
